from . import fine_categories as C

FOOD = set().union(*[
    C.FOOD_DESSERT,
    C.FOOD_DRINKS,
    C.FOOD_FRUITS,
    C.FOOD_HERB,
    C.FOOD_MEALS,
    C.FOOD_MEAT,
    C.FOOD_MISC,
    C.FOOD_NUTS,
    C.FOOD_PREP,
    C.FOOD_SPICES,
    C.FOOD_VEG
])

ANIMALS = set().union(*[
    C.ANIMALS_BIRDS,
    C.ANIMALS_FARM,
    C.ANIMALS_FISH,
    C.ANIMALS_PETS,
    C.ANIMALS_REPTILES,
    C.ANIMALS_WILD,
])

COLORS = C.COLORS

APPLIANCES = C.APPLIANCES

ELECTRONICS = set().union(*[
    C.ELECTRONICS_AUDIO,
    C.ELECTRONICS_COMM,
    C.ELECTRONICS_COMP,
    C.ELECTRONICS_DISPLAY,
    C.ELECTRONICS_MISC
])

UTENSILS = set().union(*[
    C.UTENSILS_CONTAINERS,
    C.UTENSILS_DRINKS,
    C.UTENSILS_COOKING,
    C.UTENSILS_CUTLERY,
])

TRANSPORT = set().union(*[
    C.TRANSPORT_AIR,
    C.TRANSPORT_FOURWHEEL,
    C.TRANSPORT_TWOWHEEL,
    C.TRANSPORT_GENERIC,
    C.TRANSPORT_WATER,
    C.TRANSPORT_RAIL
])

HUMANS = set().union(*[
    C.HUMANS_AGE,
    C.HUMANS_COLOR,
    C.HUMANS_COMMUTE,
    C.HUMANS_FEMALE,
    C.HUMANS_MALE,
    C.HUMANS_NEUTRAL,
    C.HUMANS_PROFESSION,
    C.HUMANS_SPORT,
])

NUMBERS = C.NUMBERS

CLOTHES = set().union(*[
    C.CLOTHES_ARMS,
    C.CLOTHES_COATS,
    C.CLOTHES_FULL_BODY,
    C.CLOTHES_HEAD,
    C.CLOTHES_LEGS,
    C.CLOTHES_NECK,
    C.CLOTHES_SCANT,
    C.CLOTHES_TORSO
])

BUILDINGS = set().union(*[*
    C.CONSTRUCTION_INDOORS,
    C.CONSTRUCTION_OUTDOORS,
    C.CONSTRUCTION_BUILDINGS,
    C.CONSTRUCTION_COMMERCIAL,
    C.CONSTRUCTION_FIXTURES,
    C.CONSTRUCTION_FURNITURE,
])

ACTIONS = C.ACTIONS

BODYPARTS = set().union(*[
    C.BODYPARTS_EXTREMITIES,
    C.BODYPARTS_FACE,
    C.BODYPARTS_HAIR,
    C.BODYPARTS_JOINTS,
    C.BODYPARTS_LIMBS,
    C.BODYPARTS_NON_HUMAN,
    C.BODYPARTS_TORSO,
])
